language: node_js

node_js:
- 0.10.39

env:
  global:
    secure: UZip6f3xjziRiLtWi35lCkixjBrLydukDVXpZix8qAGFkEe3qnMFiFchXl7X8UpLO32cdfzlwbF2cVCEwEaAlPemROs4JUc0JkYqVZoe3p6q1bMmoFdjDrElmYHWzW8UKR3uqSl0bcKQf7wm3pbdXqSd74nh7PIuRv5aL9MHHDiStWxfe2Eg60XueKiZlPLx4uMsxl4saQT0lzovSwaCmLqqWcXIIMbehXwLFB8Vv3T1+tdWWN96ALHbIDWWN9mfbN1wKcz/98IxoUKolwY2nDERByLPDSJtPO0bYEM7eUh0bzx3FsWwps8XYiLQHJdM/E4zNqk6uuR11hLUnRBYHTsLy+SIAncah29HKm4S1H0bu5BEKxOywlg9OB5MKgAqo/Yo6u71Rm7tzTjY7Mz49M3RZakGpMUPIgQPlWjuD2orKtu4OibH3J+XVD4m+W8psW0SrBK/2ka/UftBXVnOCSXpkqXVWdvugU/8GHD0NGlLcvkJCG8eg9WRXfmLVGJboBNxSvQy77guuFm49kL+PIa5Jts9G4qBaOpHfHC3hsjtUGAFz64sVBRKHGHwKfeCYS2UZGv8INjG9Nm6MqtWtbJobcyMTkMLMRJHET4j0OAj6vL03uZ8zNPVggaCbig8gioSDoJX3j720ZHVf8imVTzfzh8dN3Ewn3hkMg4TqTk=

install:
- npm install

script:
- npm test

after_success:
- npm run build
- bash deploy.bash
